//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectsw.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int order_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> NewUser_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<int> Product_id { get; set; }
    
        public virtual NewUser NewUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
